version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - client_build:/app/apps/client/build

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html # initial generation
      - client_build:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - client
      - server

      # initial generation
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html 
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email yakov.gapotchenko@gmail.com --agree-tos --no-eff-email -d yagapp.ru -d www.yagapp.ru
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html # initial generation
  #   entrypoint: >
  #     sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html; sleep 12h & wait $${!}; done"

volumes:
  client_build:
  certbot-etc:
  certbot-var:
  web-root: # initial generation
