name: Deploy Production
on:
    push:
        branches:
            - main
            - feature/docker-deploy
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy-prod:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

            - name: Deploy to Production Server
              run: |
                  ssh -o StrictHostKeyChecking=no deployer@${{ secrets.PROD_HOST }} << 'EOF'
                    cd ${{ secrets.PROD_PROJECT_PATH }}
                    git checkout feature/docker-deploy
                    git pull origin feature/docker-deploy
                    docker compose down
                    docker compose pull
                    docker compose up -d --build
                  EOF
